administracio:
    image: captwhite/administracio:latest
    container_name: administracio
    restart: always
    env_file:
      - ./.env
    networks:
      - webnet-administracio
      - proxy_network

  db:
    image: mariadb:latest
    container_name: administracio-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - webnet-administracio

  phpmyadmin:
    image: phpmyadmin
    container_name: administracio-phpmyadmin
    restart: unless-stopped
    init: true
    depends_on:
      - db
    
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: https://intranet.aster.cat/administracio/phpmyadmin/
      PMA_ARBITRARY: 1
    
    networks:
      - webnet-administracio
      - proxy_network
  

networks:
  webnet-administracio:
    external: true
  proxy_network:  
    external: true